spring:
  profiles:
    default: local
  application:
    name: Spring Cloud Gateway

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: route1
          uri: https://auth-api.root101.dev
          predicates:
            - Path=/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /latest/$\{segment}