spring:
  profiles:
    default: local
  application:
    name: Spring Cloud Gateway

---
spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8087
          predicates:
            - Path=/latest/**